# Generated by Django 3.1.6 on 2021-09-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='show_preview_features',
            field=models.BooleanField(default=False),
        ),
    ]
