# Generated by Django 3.1.6 on 2021-10-17 07:36

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_settings_show_preview_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='datalake_token',
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
