# Generated by Django 3.1.6 on 2021-10-18 04:44

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_settings_datalake_token'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='DatalakeConnection',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('owner', models.CharField(max_length=100)),
        #         ('type', models.CharField(choices=[('ONEDRIVE', 'OneDrive'), ('GOOGLE_DRIVE', 'Google Drive')], max_length=50)),
        #         ('token', fernet_fields.fields.EncryptedTextField(blank=True, null=True)),
        #     ],
        # ),
        migrations.RemoveField(
            model_name='settings',
            name='datalake_token',
        ),
        # migrations.AddField(
        #     model_name='settings',
        #     name='datalake_connection',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.datalakeconnection'),
        # ),
    ]
