# Generated by Django 3.1.6 on 2021-10-18 04:49

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20211018_0444'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='datalakeconnection',
        #     name='token',
        #     field=fernet_fields.fields.EncryptedTextField(),
        # ),
    ]
