# Generated by Django 3.1.6 on 2021-10-18 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20211018_0449'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='datalakeconnection',
        #     old_name='owner',
        #     new_name='name',
        # ),
    ]
