# Generated by Django 3.1.6 on 2021-10-19 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_auto_20211018_0451'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='datalakeconnection',
        #     old_name='token',
        #     new_name='token_cache',
        # ),
        # migrations.RenameField(
        #     model_name='datalakeconnection',
        #     old_name='name',
        #     new_name='username',
        # ),
    ]
