# Generated by Django 3.1.6 on 2021-10-29 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('settings', '0008_auto_20211019_1009'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='settings',
        #     name='datalake_connection',
        # ),
        migrations.AddField(
            model_name='settings',
            name='datalake_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='datalake_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
