# Generated by Django 3.1.6 on 2021-12-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_auto_20211029_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='delete_outdated_frequency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
