# Generated by Django 3.1.6 on 2021-12-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_settings_delete_outdated_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='delete_outdated_threshold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
