# Generated by Django 3.1.6 on 2021-12-13 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_settings_delete_outdated_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='show_preview_features',
        ),
    ]
