# Generated by Django 3.1.6 on 2021-12-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_remove_settings_show_preview_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'settings'},
        ),
    ]
