# Generated by Django 3.0.3 on 2020-08-27 11:39

from django.db import migrations, models
import saef.enums


class Migration(migrations.Migration):

    dependencies = [
        ('saef', '0003_datasetsessionmetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsession',
            name='status_type',
            field=models.CharField(choices=[('START', 'START'), ('END', 'END')], max_length=128),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_access_method',
            field=models.CharField(choices=[('TABLE', 'TABLE'), ('SQL', 'SQL')], default=saef.enums.DatasetAccess['TABLE'], max_length=32),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_type',
            field=models.CharField(choices=[('INPUT', 'INPUT'), ('OUTPUT', 'OUTPUT'), ('INTERMEDIATE', 'INTERMEDIATE'), ('TEMPORARY', 'TEMPORARY'), ('OTHER', 'OTHER')], default=saef.enums.DatasetType['INPUT'], max_length=32),
        ),
        migrations.AlterField(
            model_name='jobsession',
            name='status_type',
            field=models.CharField(choices=[('START', 'START'), ('END', 'END')], default=saef.enums.SessionStatus['START'], max_length=128),
        ),
        migrations.AlterField(
            model_name='jobsessionstatus',
            name='status_type',
            field=models.CharField(choices=[('PREPROCESSING', 'PREPROCESSING'), ('START', 'START'), ('COMPLETE', 'COMPLETE'), ('INPROGRESS', 'INPROGRESS'), ('ERROR', 'ERROR'), ('OTHER', 'OTHER'), ('POSTROCESSING', 'POSTROCESSING')], default=saef.enums.SessionProgress['START'], max_length=64),
        ),
    ]
