# Generated by Django 3.0.5 on 2020-08-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saef', '0004_datasetsession_degree_of_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetsession',
            name='degree_of_change',
            field=models.FloatField(blank=True),
        ),
    ]
