# Generated by Django 3.0.5 on 2020-08-28 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('saef', '0006_auto_20200826_1024')]

    operations = []
