# Generated by Django 3.0.5 on 2020-10-24 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saef', '0009_auto_20200930_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureBlobStorageConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_string', models.CharField(max_length=1000)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saef.Connection')),
            ],
        ),
    ]
