# Generated by Django 3.0.5 on 2020-10-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saef', '0010_azureblobstorageconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='azureblobstorageconnection',
            name='blob_name',
            field=models.CharField(default='blubber', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='azureblobstorageconnection',
            name='container_name',
            field=models.CharField(default='eimskip', max_length=500),
            preserve_default=False,
        ),
    ]
