# Generated by Django 3.1.6 on 2021-04-29 19:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saef', '0011_auto_20201025_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasource_key', models.CharField(blank=True, default=uuid.uuid4, max_length=128, unique=True)),
                ('datasource_name', models.CharField(max_length=128)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saef.connection')),
            ],
        ),
    ]
