# Generated by Django 3.1.6 on 2021-06-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saef', '0012_datasource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('description', models.TextField()),
                ('jupyter_filepath', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
    ]
