# Generated by Django 3.1.6 on 2021-06-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saef', '0013_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='thumbnail',
            field=models.ImageField(upload_to='C:\\Users\\chris\\PycharmProjects\\SAEF\\saefportal\\jupyter/dashboard/thumbnails/'),
        ),
    ]
