# Generated by Django 3.1.6 on 2021-06-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saef', '0014_auto_20210625_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='jupyter_filepath',
            new_name='jupyter_file',
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails'),
        ),
    ]
