# Generated by Django 3.1.6 on 2021-06-27 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saef', '0015_auto_20210626_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='thumbnail',
        ),
    ]
