# Generated by Django 3.1.6 on 2021-06-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saef', '0016_remove_dashboard_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails'),
        ),
    ]
