# Generated by Django 3.1.6 on 2021-06-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saef', '0017_dashboard_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
