# Generated by Django 3.1.6 on 2021-07-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saef', '0018_auto_20210628_0433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
