# Generated by Django 3.1.6 on 2021-08-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saef', '0021_auto_20210802_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(max_length=10)),
                ('dataset_update_frequency', models.CharField(max_length=10)),
                ('try_live_connection', models.BooleanField()),
            ],
        ),
    ]
