# Generated by Django 3.1.6 on 2021-08-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saef', '0025_auto_20210809_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='profile_delta_deviation',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='settings',
            name='profile_expected_datasets_n',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='settings',
            name='profile_failed_threshold',
            field=models.FloatField(default=0.5),
        ),
    ]
