# Generated by Django 3.0.3 on 2020-07-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200708_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lastname',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
