# Generated by Django 3.1.6 on 2021-09-08 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_settings_show_preview_features'),
        ('users', '0010_auto_20210907_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='settings',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.settings'),
        ),
    ]
