# Generated by Django 3.1.6 on 2021-09-10 08:38

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0011_auto_20210908_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('parents', models.ManyToManyField(blank=True, related_name='_organizationgroup_parents_+', to='users.OrganizationGroup')),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='organization_groups',
            field=models.ManyToManyField(blank=True, related_name='organization_groups', to='users.OrganizationGroup'),
        ),
    ]
