# Generated by Django 3.1.6 on 2021-09-11 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210910_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationgroup',
            name='parents',
        ),
        migrations.AddField(
            model_name='organizationgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organizationgroup'),
        ),
    ]
