# Generated by Django 3.1.6 on 2021-09-14 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_settings_show_preview_features'),
        ('users', '0014_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.settings'),
        ),
    ]
