# Generated by Django 3.1.6 on 2021-09-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210921_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcerequest',
            old_name='status_changed',
            new_name='status_changed_at',
        ),
    ]
