# Generated by Django 3.1.6 on 2021-09-22 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210921_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerequest',
            name='requesting_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
