# Generated by Django 3.1.6 on 2021-09-22 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210922_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerequest',
            name='requesting_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
