# Generated by Django 3.1.6 on 2021-09-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_objectpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectpermission',
            name='can_change',
        ),
        migrations.RemoveField(
            model_name='objectpermission',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='objectpermission',
            name='can_view',
        ),
        migrations.AddField(
            model_name='objectpermission',
            name='permission_level',
            field=models.CharField(choices=[('1', 'Level 1'), ('2', 'Level 2')], default='1', max_length=20),
        ),
    ]
