# Generated by Django 3.1.6 on 2021-09-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20210924_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcerequest',
            name='permission',
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='permission_level',
            field=models.CharField(choices=[('1', 'Level 1 (View)'), ('2', 'Level 2 (View/Update/Delete/Execute')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='resource',
            field=models.CharField(default='resource', max_length=100),
            preserve_default=False,
        ),
    ]
