# Generated by Django 3.1.6 on 2021-09-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20210924_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerequest',
            name='permission_level',
            field=models.CharField(choices=[('1', 'Level 1 (View)'), ('2', 'Level 2 (View/Update/Delete/Execute)')], default='1', max_length=20),
        ),
    ]
