# Generated by Django 3.1.6 on 2021-09-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20210925_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationgroup',
            name='object_permissions',
            field=models.ManyToManyField(blank=True, to='users.ObjectPermission'),
        ),
        migrations.AddField(
            model_name='user',
            name='object_permissions',
            field=models.ManyToManyField(blank=True, to='users.ObjectPermission'),
        ),
    ]
