# Generated by Django 3.1.6 on 2021-10-06 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_administrativeevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcerequest',
            name='permission_level',
        ),
        migrations.RemoveField(
            model_name='resourcerequest',
            name='resource',
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.objectpermission'),
            preserve_default=False,
        ),
    ]
