# Generated by Django 3.1.6 on 2021-10-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20211006_1008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResourceRequest',
            new_name='PermissionRequest',
        ),
    ]
