# Generated by Django 3.1.6 on 2021-10-06 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20211006_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrequest',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.objectpermission'),
        ),
    ]
