# Generated by Django 3.1.6 on 2021-10-07 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20211006_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionrequest',
            name='group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organization_groups',
        ),
        migrations.DeleteModel(
            name='OrganizationGroup',
        ),
    ]
