# Generated by Django 3.1.6 on 2021-10-07 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20211007_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('object_permissions', models.ManyToManyField(blank=True, to='users.ObjectPermission')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organizationgroup')),
            ],
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organizationgroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization_groups',
            field=models.ManyToManyField(blank=True, related_name='organization_groups', to='users.OrganizationGroup'),
        ),
    ]
