from .one_drive_datalake import OneDriveDatalake
from .google_drive_datalake import GoogleDriveDatalake
from .dropbox_datalake import DropboxDatalake
from .google_cloud_storage_datalake import GoogleCloudStorageDatalake
from .azure_blob_storage_datalake import AzureBlobStorageDatalake
from .azure_data_lake_datalake import AzureDataLakeDatalake
from .amazon_s3_datalake import AmazonS3Datalake
from .local_datalake import LocalDatalake
