# Generated by Django 3.1.6 on 2021-11-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalakes', '0002_googledrivedatalake'),
    ]

    operations = [
        migrations.AddField(
            model_name='googledrivedatalake',
            name='folder_ids',
            field=models.JSONField(default=dict),
        ),
    ]
