# Generated by Django 3.1.6 on 2021-11-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalakes', '0005_googlecloudstoragedatalake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlecloudstoragedatalake',
            name='root_path',
        ),
        migrations.AddField(
            model_name='googlecloudstoragedatalake',
            name='project_id',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
