# Generated by Django 3.1.6 on 2021-11-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalakes', '0006_auto_20211117_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlecloudstoragedatalake',
            name='bucket_id',
        ),
        migrations.AddField(
            model_name='googlecloudstoragedatalake',
            name='bucket_name',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
