# Generated by Django 3.1.6 on 2021-11-20 21:29

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datalakes', '0007_auto_20211120_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureBlobStorageDatalake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_account_name', models.CharField(max_length=100)),
                ('connection_string', fernet_fields.fields.EncryptedTextField()),
            ],
        ),
    ]
