# Generated by Django 3.1.6 on 2021-11-26 06:48

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datalakes', '0010_azuredatalakedatalake'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonS3Datalake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('bucket_name', models.CharField(max_length=200)),
                ('access_key_id', fernet_fields.fields.EncryptedTextField()),
                ('secret_access_key', fernet_fields.fields.EncryptedTextField()),
            ],
        ),
    ]
