# Generated by Django 3.1.6 on 2021-12-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalakes', '0012_localdatalake'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googledrivedatalake',
            old_name='folder_ids',
            new_name='object_ids',
        ),
    ]
