# Generated by Django 3.1.6 on 2021-12-15 08:15

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datalakes', '0013_auto_20211210_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazons3datalake',
            name='access_key_id',
            field=fernet_fields.fields.EncryptedCharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='amazons3datalake',
            name='secret_access_key',
            field=fernet_fields.fields.EncryptedCharField(max_length=128),
        ),
    ]
