# Generated by Django 3.0.5 on 2020-08-17 12:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saef', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualDatasetProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_count', models.IntegerField()),
                ('column_count', models.IntegerField()),
                ('hash_sum', models.IntegerField(blank=True, null=True)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saef.DatasetSession')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetComparisonRatio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_of_change', models.FloatField()),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analyzer.ActualDatasetProfile')),
            ],
        ),
        migrations.CreateModel(
            name='RatioCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('actual', models.FloatField()),
                ('expected', models.FloatField()),
                ('ratio', models.FloatField()),
                ('dataset_ratio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analyzer.DatasetComparisonRatio')),
            ],
        ),
        migrations.CreateModel(
            name='RatioColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('changes', models.BooleanField()),
                ('columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=None)),
                ('ratio', models.FloatField()),
                ('dataset_ratio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analyzer.DatasetComparisonRatio')),
            ],
        ),
        migrations.CreateModel(
            name='ExpectedDatasetProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_count', models.FloatField()),
                ('column_count', models.FloatField()),
                ('hash_sum', models.FloatField(blank=True, null=True)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saef.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='ExpectedColumnProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('min', models.CharField(blank=True, max_length=128, null=True)),
                ('max', models.CharField(blank=True, max_length=128, null=True)),
                ('uniqueness', models.FloatField()),
                ('datatype', models.CharField(max_length=128)),
                ('nullable', models.BooleanField()),
                ('order', models.IntegerField()),
                ('hash_sum', models.FloatField(blank=True, null=True)),
                ('dataset_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analyzer.ExpectedDatasetProfile')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyzeSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyzer_type', models.CharField(choices=[('ANALYZE DATASET', 'ANALYZE DATASET'), ('ANALYZE JOB', 'ANALYZE JOB'), ('ANALYZE APPLICATION', 'ANALYZE JOB'), ('ANALYZE DATASET HISTORY', 'ANALYZE DATASET HISTORY'), ('ANALYZE JOB HISTORY', 'ANALYZE JOB HISTORY'), ('ANALYZE APPLICATION HISTORY', 'ANALYZE APPLICATION HISTORY'), ('EXTERNAL', 'EXTERNAL')], default='ANALYZE DATASET', max_length=32)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saef.Application')),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saef.Dataset')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saef.Job')),
            ],
            options={
                'ordering': ('create_timestamp',),
            },
        ),
        migrations.CreateModel(
            name='ActualColumnProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('min', models.CharField(blank=True, max_length=128, null=True)),
                ('max', models.CharField(blank=True, max_length=128, null=True)),
                ('uniqueness', models.FloatField()),
                ('datatype', models.CharField(max_length=128)),
                ('nullable', models.BooleanField()),
                ('order', models.IntegerField()),
                ('hash_sum', models.IntegerField(blank=True, null=True)),
                ('dataset_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analyzer.ActualDatasetProfile')),
            ],
        ),
    ]
