# Generated by Django 3.0.3 on 2020-08-27 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saef', '0003_datasetsessionmetadata'),
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expecteddatasetprofile',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saef.DatasetSession'),
        ),
    ]
