# Generated by Django 3.0.3 on 2020-08-27 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_auto_20200827_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actualdatasetprofile',
            old_name='dataset',
            new_name='dataset_session',
        ),
        migrations.RenameField(
            model_name='expecteddatasetprofile',
            old_name='dataset',
            new_name='dataset_session',
        ),
    ]
