# Generated by Django 3.0.3 on 2020-08-28 09:00

import analyzer.enums
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_auto_20200827_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzesession',
            name='analyzer_type',
            field=models.CharField(choices=[('ANALYZE DATASET', 'ANALYZE_DATASET'), ('ANALYZE JOB', 'ANALYZE_JOB'), ('ANALYZE APPLICATION', 'ANALYZE_APPLICATION'), ('ANALYZE DATASET HISTORY', 'ANALYZE_DATASET_HISTORY'), ('ANALYZE JOB HISTORY', 'ANALYZE_JOB_HISTORY'), ('ANALYZE APPLICATION HISTORY', 'ANALYZE_APPLICATION_HISTORY'), ('EXTERNAL', 'EXTERNAL')], default=analyzer.enums.AnalyzerTask['ANALYZE_DATASET'], max_length=32),
        ),
        migrations.AlterField(
            model_name='ratiocolumn',
            name='dataset_ratio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analyzer.ActualDatasetProfile'),
        ),
        migrations.AlterField(
            model_name='ratiocount',
            name='dataset_ratio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analyzer.ActualDatasetProfile'),
        ),
        migrations.DeleteModel(
            name='DatasetComparisonRatio',
        ),
    ]
