# Generated by Django 3.0.3 on 2020-08-28 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_auto_20200828_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expecteddatasetprofile',
            name='dataset_session',
        ),
        migrations.AddField(
            model_name='expecteddatasetprofile',
            name='actual_dataset_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analyzer.ActualDatasetProfile'),
        ),
    ]
