# Generated by Django 3.1.6 on 2021-07-19 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0008_auto_20210719_2013'),
        ('analyzer', '0005_auto_20200828_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratiocolumn',
            name='dataset_ratio',
        ),
        migrations.RemoveField(
            model_name='ratiocount',
            name='dataset_ratio',
        ),
        migrations.AlterField(
            model_name='actualdatasetprofile',
            name='dataset_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datasets.datasetsession'),
        ),
        migrations.DeleteModel(
            name='AnalyzeSession',
        ),
        migrations.DeleteModel(
            name='RatioColumn',
        ),
        migrations.DeleteModel(
            name='RatioCount',
        ),
    ]
