# Generated by Django 3.1.6 on 2021-07-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_auto_20210719_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actualdatasetprofile',
            old_name='dataset_session',
            new_name='dataset_run',
        ),
    ]
