# Generated by Django 3.1.6 on 2021-07-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_auto_20210720_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualcolumnprofile',
            name='uniqueness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expectedcolumnprofile',
            name='uniqueness',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
