# Generated by Django 3.1.6 on 2021-07-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobRunHistory',
            new_name='JobRun',
        ),
    ]
