# Generated by Django 3.1.6 on 2021-07-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210703_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledjobtrigger',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='alert_on_failure_email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='alert_on_start_email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='alert_on_success_email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='schedule_cron_syntax',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='schedule_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='job',
            name='schedule_parameters',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='schedule_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
        migrations.DeleteModel(
            name='JobAlert',
        ),
        migrations.DeleteModel(
            name='ScheduledJobTrigger',
        ),
    ]
