# Generated by Django 3.1.6 on 2021-07-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20210704_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='schedule_end_time',
        ),
        migrations.RemoveField(
            model_name='job',
            name='schedule_start_time',
        ),
        migrations.AddField(
            model_name='job',
            name='schedule_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='job',
            name='schedule_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
    ]
