# Generated by Django 3.1.6 on 2021-07-07 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20210704_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=2048)),
                ('parameters', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='NotebookTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('notebook_path', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='alert_on_failure_email',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='On failure'),
        ),
        migrations.AlterField(
            model_name='job',
            name='alert_on_start_email',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='On start'),
        ),
        migrations.AlterField(
            model_name='job',
            name='alert_on_success_email',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='On success'),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_used_parameters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='internal_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.internaltask'),
        ),
        migrations.AddField(
            model_name='job',
            name='notebook_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.notebooktask'),
        ),
    ]
