# Generated by Django 3.1.6 on 2021-07-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20210709_0838'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InternalTask',
            new_name='TemplateTask',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='internal_task',
            new_name='template_task',
        ),
    ]
