# Generated by Django 3.1.6 on 2021-07-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20210709_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrun',
            name='log_file',
        ),
        migrations.AddField(
            model_name='jobrun',
            name='result',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
