# Generated by Django 3.1.6 on 2021-07-30 07:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20210723_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrun',
            name='execution_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Run Start Time'),
        ),
    ]
