# Generated by Django 3.1.6 on 2021-07-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20210730_0711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrun',
            old_name='start_time',
            new_name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='jobrun',
            name='end_time',
        ),
        migrations.AddField(
            model_name='jobrun',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Run End Time'),
        ),
    ]
