# Generated by Django 3.1.6 on 2021-07-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20210730_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrun',
            name='status',
            field=models.CharField(choices=[('SUCCEEDED', 'Succeeded'), ('SUCCEEDED_ISSUE', 'Succeeded with issue'), ('FAILED', 'Failed'), ('RUNNING', 'Running')], default='RUNNING', max_length=64),
        ),
    ]
