# Generated by Django 3.1.6 on 2021-08-23 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20210730_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrun',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_runs', to='jobs.job'),
        ),
    ]
