# Generated by Django 3.1.6 on 2021-08-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20210730_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='last_used_parameters',
        ),
        migrations.AddField(
            model_name='jobrun',
            name='parameters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
