# Generated by Django 3.1.6 on 2021-08-08 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20210807_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatetask',
            name='parameters',
        ),
    ]
