# Generated by Django 3.1.6 on 2021-08-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_remove_templatetask_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='schedule_cron_syntax',
        ),
        migrations.RemoveField(
            model_name='job',
            name='schedule_end_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='schedule_parameters',
        ),
        migrations.RemoveField(
            model_name='job',
            name='schedule_start_date',
        ),
    ]
