# Generated by Django 3.1.6 on 2021-08-26 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_historicaljob'),
        ('jobs', '0014_auto_20210823_0654'),
        ('jobs', '0016_auto_20210815_0547'),
    ]

    operations = [
    ]
