# Generated by Django 3.1.6 on 2021-08-26 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_merge_20210826_1952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalJob',
        ),
    ]
