# Generated by Django 3.1.6 on 2021-08-26 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0018_delete_historicaljob'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalJob',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('time_out', models.PositiveIntegerField(default=120)),
                ('retries', models.PositiveIntegerField(default=0)),
                ('wait_time_between_retry', models.PositiveIntegerField(default=30)),
                ('alert_on_start_email', models.CharField(blank=True, max_length=500, null=True, verbose_name='On start')),
                ('alert_on_success_email', models.CharField(blank=True, max_length=500, null=True, verbose_name='On success')),
                ('alert_on_failure_email', models.CharField(blank=True, max_length=500, null=True, verbose_name='On failure')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('notebook_task', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jobs.notebooktask')),
                ('template_task', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jobs.templatetask')),
            ],
            options={
                'verbose_name': 'historical job',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
