# Generated by Django 3.1.6 on 2021-09-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_auto_20210902_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljob',
            name='notebook_task',
            field=models.CharField(blank=True, choices=[], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='notebook_task',
            field=models.CharField(blank=True, choices=[], max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='NotebookTask',
        ),
    ]
