# Generated by Django 3.1.6 on 2021-09-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_auto_20210903_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljob',
            name='notebook_task',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='notebook_task',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
