# Generated by Django 3.1.6 on 2021-09-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_auto_20210903_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaljob',
            name='alert_on_failure_email',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='alert_on_start_email',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='alert_on_success_email',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='notebook_task',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='retries',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='template_task',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='time_out',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='wait_time_between_retry',
        ),
    ]
