# Generated by Django 3.1.6 on 2021-09-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_auto_20210904_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljob',
            name='name',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
    ]
