# Generated by Django 3.1.6 on 2021-12-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_job_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='notebook_task',
        ),
        migrations.AlterField(
            model_name='job',
            name='template_task',
            field=models.CharField(choices=[('PROFILE_DATASET', 'Profile dataset'), ('REFRESH_DATA', 'Refresh data'), ('EXTRACT_METADATA', 'Extract metadata')], default='test', max_length=64),
            preserve_default=False,
        ),
    ]
