# Generated by Django 3.1.6 on 2022-01-21 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_auto_20211214_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='retries',
        ),
        migrations.RemoveField(
            model_name='job',
            name='time_out',
        ),
        migrations.RemoveField(
            model_name='job',
            name='wait_time_between_retry',
        ),
    ]
