# Generated by Django 3.1.6 on 2021-10-30 10:20

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datastores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azuredatastore',
            name='password',
            field=fernet_fields.fields.EncryptedCharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='postgresdatastore',
            name='password',
            field=fernet_fields.fields.EncryptedCharField(max_length=128),
        ),
    ]
