# Generated by Django 3.1.6 on 2021-11-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastores', '0004_googledrivedatastore'),
    ]

    operations = [
        migrations.AddField(
            model_name='googledrivedatastore',
            name='root_folder_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
