# Generated by Django 3.1.6 on 2021-11-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastores', '0005_googledrivedatastore_root_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='googledrivedatastore',
            name='folder_names',
            field=models.JSONField(default=dict),
        ),
    ]
