# Generated by Django 3.1.6 on 2021-11-18 09:49

import datastores.mixins
from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datastores', '0007_dropboxdatastore'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCloudStorageDatastore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('project_id', models.CharField(max_length=500)),
                ('token_cache', fernet_fields.fields.EncryptedTextField()),
                ('bucket_name', models.CharField(max_length=500)),
            ],
            bases=(datastores.mixins.GetConnectionMixin, models.Model),
        ),
    ]
