# Generated by Django 3.1.6 on 2021-11-23 06:02

import datastores.mixins
from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datastores', '0008_googlecloudstoragedatastore'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureBlobStorageDatastore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_account_name', models.CharField(max_length=100)),
                ('container_name', models.CharField(max_length=200)),
                ('connection_string', fernet_fields.fields.EncryptedTextField()),
            ],
            bases=(datastores.mixins.GetConnectionMixin, models.Model),
        ),
    ]
